// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gkgxcosbnpgqvjchmgji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdrZ3hjb3NibnBncXZqY2htZ2ppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NTUzNjMsImV4cCI6MjA2ODUzMTM2M30.aytB_kxrJNd3aoffD4LTTNdb_eIeCzs6UaQ8CfRzLTw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});